repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
      - id: terraform_checkov
      - id: terrascan
        args:
          - --args=--non-recursive
      - id: terraform_tflint
      - id: terraform_validate
        args:
          - --init-args=-backend=false
